myproj/foodblog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'foodblog'

urlpatterns = [
    # food_list view as a class
    path('', views.FoodListView.as_view(), name='food_list'),

    # food_detail view as a class
    # path('<slug:slug>',views.FoodDetailView.as_view(),name='food_detail'),

    # food_list view as a function
    # url(r'^$',views.food_list,name='food_list'),

    # food_detail view as a function
    # food_detail view as a function
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/' \
        r'(?P<food>[-\w]+)/$',
        views.food_detail,
        name='food_detail'
        ),

    # food_share view as a function
    url(r'^(?P<food_id>\d+)/share/$',
        views.food_share,
        name='food_share'),

]

myproj/myproj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # foodblog app
    path(r'foodblog/', include(('foodblog.urls', 'foodblog')
                               )
         ),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproj/foodblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class Food(models.Model):
    ''' Food Model - etc'''
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=20)
    slug = models.SlugField(max_length=30, unique_for_date='publish')
    author = models.ForeignKey(User,
                               related_name='foodblog_food',
                               on_delete=models.CASCADE, )
    pic = models.ImageField(upload_to='food_pic',blank=True,null=True,)
    desc = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('foodblog:food_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug]
                       )


# -------------------------------------------------------------------------
class Comment(models.Model):
    food = models.ForeignKey(Food,
                             related_name='comments',
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.food)

myproj/foodblog/forms.py
from django import forms

class EmailFoodForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


from .models import Comment
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

myproj/foodblog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Food, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from .forms import EmailFoodForm, CommentForm


# Create your views here.
# food_list view as a class
class FoodListView(ListView):
    queryset = Food.objects.all()
    context_object_name = 'foods'
    paginate_by = 3
    template_name = 'foodblog/food/list.html'


# food_detail view as a class
class FoodDetailView(DetailView):
    model = Food
    context_object_name = 'food'
    template_name = 'foodblog/food/detail.html'


# --------------------------------------------------------------------------
# food_list view as a function
def food_list(request):
    object_list = Food.objects.all()
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        foods = paginator.page(page)
    except PageNotAnInteger:  # If page is not an integer deliver the first page
        foods = paginator.page(1)
    except EmptyPage:  # If page is out of range deliver last page of results
        foods = paginator.page(paginator.num_pages)

    return render(
        request,
        'foodblog/food/list.html',
        {'page': page,
         'foods': foods}
    )


# ------------------------------------------------------
# food_detail view as a function
def food_detail(request, year, month, day, food):
    food = get_object_or_404(
        Food,
        slug=food,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day
    )

    # List of active comments for this post
    comments = food.comments.filter(active=True)
    commented=False
    if request.method == 'POST': # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid(): # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False) # Assign the current post to the comment
            new_comment.food = food # Save the comment to the database
            new_comment.save()
            commented=True
    else:
        comment_form = CommentForm()

    return render(
        request,
        'foodblog/food/detail.html',
        {'food': food,
         'commented':commented,
         'comments': comments,
         'comment_form': comment_form}
    )


# ---------------------------------------------------------------
# food_share view as a function

from django.core.mail import send_mail


def food_share(request, food_id):
    # Retrieve food by id
    food = get_object_or_404(Food, id=food_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailFoodForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            food_url = request.build_absolute_uri(food.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'],
                                                                   cd['email'],
                                                                   food.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(food.title,
                                                                     food_url,
                                                                     cd['name'],
                                                                     cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailFoodForm()
    return render(request,
                  'foodblog/food/share.html',
                  {'food': food,
                   'form': form,
                   'sent': sent}
                  )

myproj/foodblog/templates/foodblog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/foodblog.css' %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <br>
    <hr>
    <br>
    <div id="sidebar">
        <h2>My foodblog</h2>
        <p>This is my foodblog.</p>
    </div>
</body>
</html>

myproj/foodblog/templates/foodblog/food/detail.html
{% extends "foodblog/base.html" %}
{% block title %}{{ food.title }}{% endblock %}
{% block content %}
    <h1>{{ food.title }}</h1>
	<br><hr><br>
		<img src="{{food.pic.url}}" alt="food pic"/>
	<br><hr><br>
    <p class="date">
        Published {{ food.publish }} by {{ food.author }}
    </p>
    {{ food.desc|linebreaks }}
    <p>
        <a href="{% url 'foodblog:food_share' food.id %}">
            Share this post
        </a>
    </p>
    <br>
    <hr>
    <br>
    {% with comments.count as total_comments %}
		<h2>
			{{ total_comments }} comment{{ total_comments|pluralize }}
		</h2>
	{% endwith %}
	{% for comment in comments %}
		<div class="comment">
			<p class="info" style="color:red;">
				Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
			</p>
		{{ comment.body|linebreaks }}
		</div>
		{% empty %}
		<p>There are no comments yet.</p>
	{% endfor %}


	{% if commented %}
			<h2>Your comment has been added.</h2>
	{% else %}
		<br><hr><br>
		<h2>Add a new comment</h2>
		<form action="." method="post">
			{{ comment_form.as_p }}
			{% csrf_token %}
			<p><input type="submit" value="Add comment"></p>
		</form>
	{% endif %}


{% endblock %}

myproj/foodblog/templates/foodblog/food/list.html
{% extends "foodblog/base.html" %}
{% block title %}My FoodBlog Application{% endblock %}
{% block content %}
    <h1>My FoodBlog</h1>
    {% for food in foods %}
        <h2>
            <a href="{{ food.get_absolute_url }}">
            {{ food.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ food.publish }} by {{ food.author }}
        </p>
        {{ food.desc|truncatewords:30|linebreaks }}
    {% endfor %}
    <br><hr><br>
    {% include "pagination.html" with page=page_obj %}


{% endblock %}

myproj/foodblog/templates/foodblog/food/share.html
{% extends "foodblog/base.html" %}
{% block title %}Share a Food{% endblock %}
{% block content %}
	{% if sent %}
		<h1>E-mail successfully sent</h1>
		<p>
			"{{ food.title }}" was successfully sent to {{ cd.to }}.
		</p>
	{% else %}
		<h1>Share "{{ food.title }}" by e-mail</h1>
		<form action="." method="post">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Send e-mail">
		</form>
	{% endif %}
{% endblock %}

myproj/foodblog/templates/pagination.html
<div class="pagination">
	<span class="step-links">
		{% if page.has_previous %}
			<a href="?page={{ page.previous_page_number }}">Previous</a>
		{% endif %}
		<span class="current">
			Page {{ page.number }} of {{ page.paginator.num_pages }}.
		</span>
		{% if page.has_next %}
			<a href="?page={{ page.next_page_number }}">Next</a>
		{% endif %}
	</span>
</div>